### ISSUE TITLE
Custom utop instructions are not very clear

### ISSUE THREAD

**Issue by samrat** [diml/utop#211]
Following the older example in this repo, I had a `.mltop` file to do this but I'm restructuring my project dir to have subdirectories. To get a custom utop working again, I tried following the new example and instructions but I found the documentation/example code a bit lacking:

1. The jbuilder example folder doesn't give any clue on how to actually build a custom utop-- running `jbuilder build myutop.o` produces a `.o` file. How do I then produce an executable? (The older example had a Makefile which produced a binary.)
2. IMO, the example should be a bit "realistic" to show how to build custom utop with multiple modules across sub-directories.

**Comment by diml** [comment]
Indeed, I updated the instructions in the main README and added a README in examples/custom-utop.

Regarding splitting your modules between several directories, currently jbuilder doesn't support libraries and executables split across several directories. This question is essentially left out until OCaml supports namespaces. For now I would recommend defining one library per directory, which is easy to do with jbuilder. Alternatively there is a PR to make this scheme work: https://github.com/janestreet/jbuilder/pull/35

**Comment by shonfeder** [comment]
I would think one of the main reasons to build a custom top-level would be to load up your development modules without having to explicitly install and `#require` them. But I cannot seem to figure out how this can best be done (outside of configuring a local `.ocaminit` for each project, but then I'm not sure why I'd need a custom top level)? Am I mistaken? If not, would it be possible to also indicate how one sets up the custom top-level (using jbuilder?), so that it has your in-development modules available in the environment by default?

**Comment by diml** [comment]
There is a work in progress in jbuilder to do all this automatically: https://github.com/janestreet/jbuilder/pull/183

**Comment by shonfeder** [comment]
Ah! Well that explains why there isn't documentation on how to do this yet. :) Thanks!
